### ISSUE TITLE
Not fast enough?

### ISSUE THREAD

**Issue by columna1** [columna1/Snes-input-display#1]
With the teensy 2.0 the console seems to be too fast to work with the teensy. Will probably need to upgrade to a teensy 3.1 in order to keep up

**Comment by jcmnn** [comment]
It's now in a semi-working state. The menu seems to work fine but it does not work in games.

**Comment by jcmnn** [comment]
The controller now works in games. Settings the serial data to low instead of high after all 16 clocks were pulsed did the trick.

**Comment by columna1** [comment]
seems to be fast enough for a third party console (retro duo) but a it seems to not be able to keep up with a real snes

**Comment by columna1** [comment]
changed the code to poll in between frames, should fix speed issues
